//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        internal int productId;

        public int ProductId { get; set; }
        public string ProductName { get; set; }
        public string ProductDescr { get; set; }
        public Nullable<int> ProductRating { get; set; }
        public string ProductReview { get; set; }
    }
}
